sudo: false
language: php
php:
  - "7.0"
install:
  - composer self-update
  - composer install
script:
  - ./vendor/bin/phpcs --standard=PSR2 --ignore=vendor,test,config,data,autoload_classmap.php --extensions=php ./
cache:
  directories:
    - $HOME/.composer/cache
matrix:
  fast_finish: true
